---
http:
  routers:
    instance5:
      rule: Host(`instance5.docker.localhost`)
      middlewares: instance5-redirect,instance5-error-handling
      service: instance1@docker

    instance5-ssl:
      rule: Host(`instance5.docker.localhost`)
      tls: true
      middlewares: instance5-redirect,instance5-error-handling
      service: instance1@docker

  middlewares:
    instance5-redirect:
      redirectScheme:
        scheme: https
        permanent: true

    instance5-error-handling:
      errors:
        status: 500,502,503,504
        service: default-nginx-proxy@docker
        query: /{status}.html
